# Numpy

In [8]:
#Import Numpy Library

import numpy as np
from numpy import random

In [2]:
#create simple array from the list 

arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
arr.ndim # DIMENSION

2

In [4]:
arr.shape # shape of array

(2, 4)

In [5]:
type(arr)

numpy.ndarray

In [7]:
arr.data #memory location

# RANDOM NUMBER GENERATOR USING NUMPY

In [12]:
x= random.randint(1000)
x

501

In [13]:
x= random.rand(10)
x

array([0.20488213, 0.19414684, 0.80412103, 0.99726026, 0.49071792,
       0.40668588, 0.7542358 , 0.09855818, 0.03325831, 0.14323838])

In [14]:
x= random.rand(5)
x

array([0.63375904, 0.32790982, 0.79870111, 0.30674096, 0.22886467])

In [15]:
x= random.randint(100,size=(5))
x

array([82, 74,  1, 17, 16])

In [16]:
x= random.randint(100,size=(5,3))
x

array([[36, 92, 64],
       [94, 44, 37],
       [67, 19, 51],
       [46, 98, 39],
       [23, 33, 15]])

In [25]:
#a=1D array ,with 7 integer
#b=1D array ,with 7 integer
#math operation.

a= random.randint(100,size=(5))
print(a)
b= random.randint(100,size=(5))
print(b)

c = a + b
print(c)

[46 68 61 69 12]
[64 31 49 91 54]
[110  99 110 160  66]


# Matrix in Numpy

In [26]:
a=np.matrix('1 2; 3 4')
a

matrix([[1, 2],
        [3, 4]])

In [28]:
a=np.matrix('1 2 3; 4 5 6 ;7 8 9')
a

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [29]:
b = np.matrix([[1,2,3,4],[5,6,7,8]])
b

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

# Measurement of central Tendency

In [30]:
arr = np.array([[1,2,3],[5,6,7],[8,9,10]])
arr

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [31]:
np.amin(arr)

1

In [32]:
np.amax(arr)  #maxvalue

10

In [33]:
np.mean(arr)

5.666666666666667

In [35]:
np.median(arr)

6.0

In [36]:
np.std(arr) #std.deviation

2.9814239699997196

In [37]:
np.var(arr)

8.88888888888889